export const SET_PAGE_CONTENT = "SET_PAGE_CONTENT";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";

export const USER_BEGIN_LOGIN = "USER_BEGIN_LOGIN";
export const USER_SUCCESS_LOGIN = "USER_SUCCESS_LOGIN";
export const USER_FAIL_LOGIN = "USER_FAIL_LOGIN";
export const USER_REMENBER_LOGIN = "USER_REMENBER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";